name: Build application (Docker) - Main

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  docker:
        runs-on: ubuntu-latest
        steps:
          -
            name: Checkout
            uses: actions/checkout@v3
          -
            name: Set up QEMU
            uses: docker/setup-qemu-action@v2
          -
            name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v2
          -
            name: Login to Docker Hub
            uses: docker/login-action@v2
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
          -
            name: Build and push
            uses: docker/build-push-action@v4
            with:
              context: .
              push: true
              tags: davidgoncalvesz/app-gitops:main-${{ github.run_number }}

          -
            name: Run Docker container for testing
            run: docker run -p 3000:3000 app-gitops:main-${{ github.run_number }}

          -
            name: run docker for testing
            run: docker run -p 3000:3000 app-gitops:main-${{ github.run_number }}

          - name: Test
            run: |
              sleep 5  # Give the container some time to start
              curl http://localhost:3000/health
              curl http://localhost:3000/
  modifygit:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: changing the deployment of git repo
        with:
          repository: 'davidgoncalvesz/cops-kubernetes-charts'
          token: ${{ secrets.GIT_PASSWORD }}
      - name: modify the image
        run: |
          git config user.email david.viragoncalves@student.ucll.be
          git config user.name davidgoncalvesz
          pwd
          cat helm/values.yaml
          pwd
          sed -i "s+davidgoncalvesz/app-gitops:main-.*+davidgoncalvesz/app-gitops:main-$RUN_NUMBER+g" helm/values.yaml
          cat helm/values.yaml
          git add .
          git commit -m 'Done  by Github Actions   Job changemanifest: ${{ github.run_number }}'
          git push origin main
        env:
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
          RUN_NUMBER: ${{ github.run_number }}
